$file = 'c:\Users\Alex\Documents\DEV\GITHUB\SCRIPT-WINDOWS-ALEEXLEDEV\Scripts-by-AleexLeDev.bat'
$lines = [System.IO.File]::ReadAllLines($file, [System.Text.Encoding]::UTF8)

$start = -1
$end = -1
for ($i=0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -match '^:wan_public_scan') { $start = $i }
    if ($start -gt -1 -and $lines[$i] -match '^:cyber_remote_menu') { $end = $i; break }
}

$newBlock = @(
    ':wan_public_scan',
    'cls',
    'echo.',
    'echo %B%  ================================================%N%',
    'echo %B%   SCAN DES FAILLES ET PORTS (WAN/LAN)%N%',
    'echo %B%  ================================================%N%',
    'echo.',
    'echo  %Y%[i] Cible :%N% !remote_ip!',
    'echo  %Y%[i]%N% Resolution et analyse complete en cours...',
    'echo  %Y%[i]%N% Appuyez sur ECHAP pour annuler.',
    'echo.',
    '',
    'set "WANS=%TEMP%\wan_scan_%RANDOM%.ps1"',
    'if exist "%WANS%" del /f /q "%WANS%"',
    '',
    '>>  "%WANS%" echo $ip = "!remote_ip!"',
    '>>  "%WANS%" echo $wanPorts = @(',
    '>>  "%WANS%" echo     @{P=21;  N="FTP";         R="MEDIUM";   H="Transfert fichiers en clair"},',
    '>>  "%WANS%" echo     @{P=22;  N="SSH";         R="HIGH";     H="Terminal complet possible !"},',
    '>>  "%WANS%" echo     @{P=23;  N="Telnet";      R="HIGH";     H="Protocole sans chiffrement"},',
    '>>  "%WANS%" echo     @{P=25;  N="SMTP";        R="LOW";      H="Serveur mail"},',
    '>>  "%WANS%" echo     @{P=53;  N="DNS";         R="LOW";      H="Resolution de noms"},',
    '>>  "%WANS%" echo     @{P=80;  N="HTTP";        R="LOW";      H="Interface web / HTTP non chiffré"},',
    '>>  "%WANS%" echo     @{P=110; N="POP3";        R="MEDIUM";   H="Serveur mail entrant"},',
    '>>  "%WANS%" echo     @{P=135; N="RPC";         R="HIGH";     H="Service RPC Windows"},',
    '>>  "%WANS%" echo     @{P=139; N="NetBIOS";     R="HIGH";     H="Partages locaux Windows"},',
    '>>  "%WANS%" echo     @{P=143; N="IMAP";        R="MEDIUM";   H="Serveur mail entrant"},',
    '>>  "%WANS%" echo     @{P=443; N="HTTPS";       R="LOW";      H="Interface web securisee"},',
    '>>  "%WANS%" echo     @{P=445; N="SMB";         R="CRITICAL"; H="EternalBlue / WannaCry risque !"},',
    '>>  "%WANS%" echo     @{P=465; N="SMTPS";       R="LOW";      H="Serveur mail securise"},',
    '>>  "%WANS%" echo     @{P=587; N="SMTP";        R="LOW";      H="Serveur mail soumis"},',
    '>>  "%WANS%" echo     @{P=993; N="IMAPS";       R="LOW";      H="Serveur mail securise"},',
    '>>  "%WANS%" echo     @{P=995; N="POP3S";       R="LOW";      H="Serveur mail securise"},',
    '>>  "%WANS%" echo     @{P=1433;N="MSSQL";       R="CRITICAL"; H="BDD SQL Server exposee !"},',
    '>>  "%WANS%" echo     @{P=1521;N="Oracle";      R="CRITICAL"; H="BDD Oracle exposee !"},',
    '>>  "%WANS%" echo     @{P=2049;N="NFS";         R="HIGH";     H="Partage de fichiers Linux"},',
    '>>  "%WANS%" echo     @{P=3306;N="MySQL";       R="CRITICAL"; H="Base de donnees exposee !"},',
    '>>  "%WANS%" echo     @{P=3389;N="RDP";         R="HIGH";     H="Bureau a distance Windows"},',
    '>>  "%WANS%" echo     @{P=5432;N="PostgreSQL";  R="CRITICAL"; H="Base de donnees exposee !"},',
    '>>  "%WANS%" echo     @{P=5900;N="VNC";         R="HIGH";     H="Acces ecran a distance"},',
    '>>  "%WANS%" echo     @{P=5985;N="WinRM";       R="HIGH";     H="PowerShell distant Windows"},',
    '>>  "%WANS%" echo     @{P=8080;N="HTTP-Alt";    R="MEDIUM";   H="Interface admin ou proxy"},',
    '>>  "%WANS%" echo     @{P=8443;N="HTTPS-Alt";   R="MEDIUM";   H="Interface admin securisee"}',
    '>>  "%WANS%" echo ^)',
    '>>  "%WANS%" echo if ("!remote_port!" -ne "NONE" -and "!remote_port!" -match "^\d+$") { $wanPorts += @{P=[int]"!remote_port!"; N="Port Custom"; R="HIGH"; H="Port specifie manuellement"} }',
    '>>  "%WANS%" echo $found = @()',
    '>>  "%WANS%" echo foreach ($e in $wanPorts) {',
    '>>  "%WANS%" echo     $esc = $false',
    '>>  "%WANS%" echo     if ($Host.UI.RawUI.KeyAvailable) { if ($Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown").VirtualKeyCode -eq 27) { $esc=$true } }',
    '>>  "%WANS%" echo     if ($esc) { break }',
    '>>  "%WANS%" echo     [Console]::Write("`r  [*] Test port $($e.P) ($($e.N))...    ")',
    '>>  "%WANS%" echo     $tcp = New-Object System.Net.Sockets.TcpClient',
    '>>  "%WANS%" echo     try {',
    '>>  "%WANS%" echo         $c = $tcp.BeginConnect($ip, $e.P, $null, $null)',
    '>>  "%WANS%" echo         if ($c.AsyncWaitHandle.WaitOne(800, $false) -and $tcp.Connected) {',
    '>>  "%WANS%" echo             $col = switch($e.R){ "CRITICAL"{"Magenta"}; "HIGH"{"Red"}; "MEDIUM"{"Yellow"}; default{"Cyan"} }',
    '>>  "%WANS%" echo             Write-Host ("`r  [PORT OUVERT] $($e.P.ToString().PadRight(5)) $($e.N.PadRight(12)) [$($e.R.PadRight(8))] $($e.H)") -f $col',
    '>>  "%WANS%" echo             $found += $e',
    '>>  "%WANS%" echo         }',
    '>>  "%WANS%" echo     } catch {} finally { $tcp.Close() }',
    '>>  "%WANS%" echo }',
    '>>  "%WANS%" echo [Console]::Write("`r" + (" " * 55) + "`r")',
    '>>  "%WANS%" echo Write-Host ""',
    '>>  "%WANS%" echo if ($found.Count -eq 0) {',
    '>>  "%WANS%" echo     Write-Host "  [OK] Aucun port critique expose depuis internet." -f Green',
    '>>  "%WANS%" echo     Write-Host "  [i] La box bloque tout. Utilisez un piege pour penetrer le LAN interne." -f Yellow',
    '>>  "%WANS%" echo     Set-Content "$env:TEMP\wan_open_ports.txt" "" -Encoding ASCII',
    '>>  "%WANS%" echo } else {',
    '>>  "%WANS%" echo     Write-Host "  [$($found.Count) service(s) expose(s) detecte(s) - Failles potentielles !]" -f Red',
    '>>  "%WANS%" echo     $found ^| ForEach-Object { "$($_.P)^|$($_.N)^|$($_.R)" } ^| Set-Content "$env:TEMP\wan_open_ports.txt" -Encoding ASCII',
    '>>  "%WANS%" echo }',
    '',
    'powershell -NoProfile -ExecutionPolicy Bypass -File "%WANS%"',
    'if exist "%WANS%" del /f /q "%WANS%"',
    '',
    'echo.',
    'set "fwd_opts=Retour"',
    'set "fwd_actions=retour"',
    '',
    'findstr /C:"3389|" "%TEMP%\wan_open_ports.txt" >nul 2>&1',
    'if %errorlevel%==0 (set "fwd_opts=Tenter connexion RDP (Bureau a distance) sur port 3389;!fwd_opts!" & set "fwd_actions=rdp,!fwd_actions!")',
    '',
    'findstr /C:"22|" "%TEMP%\wan_open_ports.txt" >nul 2>&1',
    'if %errorlevel%==0 (set "fwd_opts=Tenter connexion SSH sur port 22;!fwd_opts!" & set "fwd_actions=ssh,!fwd_actions!")',
    '',
    'findstr /C:"5985|" "%TEMP%\wan_open_ports.txt" >nul 2>&1',
    'if %errorlevel%==0 (set "fwd_opts=Ouvrir session PowerShell distante (WinRM) sur port 5985;!fwd_opts!" & set "fwd_actions=winrm,!fwd_actions!")',
    '',
    'findstr /C:"445|" "%TEMP%\wan_open_ports.txt" >nul 2>&1',
    'if %errorlevel%==0 (set "fwd_opts=Explorer partages secrets SMB (C$, Admin$);!fwd_opts!" & set "fwd_actions=smb,!fwd_actions!")',
    '',
    'call :DynamicMenu "QUE FAIRE AVEC CETTE CIBLE ?" "!fwd_opts!" "NONUMS NOCLS"',
    'set "fwd_ch=%errorlevel%"',
    '',
    'if "%fwd_ch%"=="0" goto cyber_ip_grabber',
    '',
    'set "idx=0"',
    'for %%A in (!fwd_actions!) do (',
    '    set /a idx+=1',
    '    if "!idx!"=="!fwd_ch!" set "sel_action=%%A"',
    ')',
    '',
    'if "!sel_action!"=="rdp" (',
    '    echo.',
    '    echo  [i] Lancement connexion Bureau a distance vers !remote_ip!...',
    '    start mstsc /v:!remote_ip!',
    '    pause',
    '    goto wan_public_scan',
    ')',
    'if "!sel_action!"=="ssh" (',
    '    echo.',
    '    echo  [i] Connexion SSH vers !remote_ip!...',
    '    set /p "ssh_user=Utilisateur cible : "',
    '    if not defined ssh_user goto wan_public_scan',
    '    ssh !ssh_user!@!remote_ip!',
    '    pause',
    '    goto wan_public_scan',
    ')',
    'if "!sel_action!"=="winrm" (',
    '    cls',
    '    echo.',
    '    echo [i] Tentative de connexion WinRM Remote PowerShell sur !remote_ip!...',
    '    powershell -NoProfile -Command "Enter-PSSession -ComputerName !remote_ip! -Credential (Get-Credential)"',
    '    pause',
    '    goto wan_public_scan',
    ')',
    'if "!sel_action!"=="smb" goto smb_explore',
    'if "!sel_action!"=="retour" goto cyber_remote_menu',
    'goto cyber_remote_menu',
    ''
)

if ($start -gt -1 -and $end -gt $start) {
    if ($end - $start -gt 5) {
        $lines = $lines[0..($start-1)] + $newBlock + $lines[$end..($lines.Count-1)]
        $enc = New-Object System.Text.UTF8Encoding $false
        [System.IO.File]::WriteAllLines($file, $lines, $enc)
        Write-Host "[OK] wan_public_scan replaced" -f Green
    } else { Write-Host "Invalid block size $start to $end" }
} else {
    Write-Host "Not found"
}
